import {chromium,expect} from '/Users/gaowenlong/Desktop/atoms/node_modules/@playwright/test/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
expect.configure({timeout:30000});
const fixture=readFileSync('/Users/gaowenlong/Desktop/atoms/tests/browser/candidate.spec.ts','utf8');
const html=fixture.match(/const html = `([\s\S]*?)`;/)![1];
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage(); await page.addInitScript('window.__name=(fn)=>fn');
const report:any={};
await page.route('**/api/generate',route=>route.fulfill({json:{html,model:'controlled-fixture',durationMs:1,generatedAt:'base'}}));
await page.goto('http://127.0.0.1:3107/');
await page.getByLabel('你想做什么？').fill('独立评审保存中切换');
await page.getByRole('button',{name:'开始生成'}).click();
await expect(page.getByText('项目已保存',{exact:true})).toBeVisible();
let f=page.frameLocator('iframe');
await f.getByLabel('任务',{exact:true}).fill('已提交基线');
await f.getByRole('button',{name:'添加',exact:true}).press('Enter');
await expect(page.getByText('应用数据已保存',{exact:true})).toBeVisible();
await page.unroute('**/api/generate');
let pendingRoute:any;
await page.route('**/api/generate',route=>{pendingRoute=route});
await page.getByLabel('追加修改需求').fill('添加标题');
await page.getByRole('button',{name:'生成候选',exact:true}).click();
await page.evaluate(()=>{const original=IDBDatabase.prototype.transaction;let held=false;const control=window as any;IDBDatabase.prototype.transaction=function(...args:any[]){const tx=original.apply(this,args as any);if(args[1]==='readwrite'&&!held){held=true;control.holdingSave=true;const store=tx.objectStore('applicationData');const pump=()=>{store.get('__hold__').onsuccess=()=>{if(!control.releaseSave)pump()}};pump()}return tx}});
await f.getByLabel('任务',{exact:true}).fill('生成等待期间的正式新增');
await f.getByRole('button',{name:'添加',exact:true}).press('Enter');
await expect(page.locator('.data-status')).toContainText('正在保存');
await expect.poll(()=>!!pendingRoute).toBeTruthy();
await pendingRoute.fulfill({json:{html:html.replace('<body>','<body><h1>审查候选</h1>'),model:'controlled-fixture',durationMs:1,generatedAt:'candidate'}});
await page.waitForTimeout(250);
report.whilePending={candidateCount:await f.getByRole('heading',{name:'审查候选'}).count(),generating:await page.getByRole('button',{name:'正在生成候选…'}).count()};
await page.evaluate(()=>{(window as any).releaseSave=true});
await expect(f.getByRole('heading',{name:'审查候选'})).toBeVisible();
await expect(f.getByText('生成等待期间的正式新增',{exact:true})).toBeVisible();
report.candidateContainsCommittedEdit=true; writeFileSync('/tmp/atoms-m2-review/spec-edge-pending-partial.json',JSON.stringify(report,null,2));
await f.getByLabel('任务',{exact:true}).fill('不应写回的试用新增');
await f.getByRole('button',{name:'添加',exact:true}).press('Enter');
await expect(page.locator('.data-status')).toContainText('仅本轮会话有效');
await page.getByRole('button',{name:'采用修改',exact:true}).click();
await expect(page.getByText('运行预览 · 已采用应用')).toBeVisible({timeout:30000});
await expect(f.getByText('生成等待期间的正式新增',{exact:true})).toBeVisible();
await expect(f.getByText('不应写回的试用新增',{exact:true})).toHaveCount(0);
report.adoptionPreservesCommittedOfficialEditAndExcludesTrial=true;
await page.reload();
await expect(f.getByText('生成等待期间的正式新增',{exact:true})).toBeVisible();
await expect(page.getByLabel('已采用修改记录').locator('li')).toHaveCount(1);
report.reloadRestores=true;
writeFileSync('/tmp/atoms-m2-review/spec-edge-pending.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
await browser.close();
